version: '3.8'

services:
  backend:
    build: .
    container_name: movie_backend
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://enjirapunikhil_db_user:Nikhil123@cluster0.5ndbdhn.mongodb.net/movie_db?retryWrites=true&w=majority&appName=Cluster0&uuidRepresentation=standard
    ports:
      - "8080:8080"
    networks:
      - movie_network

  frontend:
    build: frontend/
    container_name: movie_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge
